# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.cache/wt [current_project]
set_property parent.project_path /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/harsha/work/Zynq/workspace/ip-repo/Volume_Pregain
  /home/harsha/work/Zynq/workspace/ip-repo/SoC_Design/IPs/Audio_Mixer
  /home/harsha/work/Zynq/workspace/ip_repo/axi_to_audio_interface_1.0
  /home/harsha/work/Zynq/workspace/ip-repo/ip_repo_vivado
  /home/harsha/work/Zynq/workspace/ip_repo/audio_to_axi_interface_1.0
  /home/harsha/work/Zynq/workspace/ip-repo/zedboard_audio
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/Audio_Mixer_Design.bd
set_property used_in_implementation false [get_files -all /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_processing_system7_0_0/Audio_Mixer_Design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_rst_processing_system7_0_100M_0/Audio_Mixer_Design_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_rst_processing_system7_0_100M_0/Audio_Mixer_Design_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_rst_processing_system7_0_100M_0/Audio_Mixer_Design_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_xbar_0/Audio_Mixer_Design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_auto_pc_0/Audio_Mixer_Design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/Audio_Mixer_Design_ooc.xdc]
set_property is_locked true [get_files /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/Audio_Mixer_Design.bd]

read_vhdl -library xil_defaultlib /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/sources_1/bd/Audio_Mixer_Design/hdl/Audio_Mixer_Design_wrapper.vhd
read_xdc /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/constrs_1/imports/constraints/zed_audio.xdc
set_property used_in_implementation false [get_files /home/harsha/work/Zynq/workspace/Audio_Mixer_1.1/Audio_Mixer_1.1.srcs/constrs_1/imports/constraints/zed_audio.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top Audio_Mixer_Design_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef Audio_Mixer_Design_wrapper.dcp
catch { report_utilization -file Audio_Mixer_Design_wrapper_utilization_synth.rpt -pb Audio_Mixer_Design_wrapper_utilization_synth.pb }
