# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zed_audio.xdc

# Block Designs: bd/Audio_Mixer_Design/Audio_Mixer_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design || ORIG_REF_NAME==Audio_Mixer_Design}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_processing_system7_0_0/Audio_Mixer_Design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_processing_system7_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_processing_system7_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_zed_audio_0_0/Audio_Mixer_Design_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_zed_audio_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_zed_audio_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_xlconstant_0_0/Audio_Mixer_Design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_xlconstant_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_xlconstant_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_audio_to_axi_interface_0_0/Audio_Mixer_Design_audio_to_axi_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_audio_to_axi_interface_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_audio_to_axi_interface_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_processing_system7_0_axi_periph_0/Audio_Mixer_Design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==Audio_Mixer_Design_processing_system7_0_axi_periph_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_rst_processing_system7_0_100M_0/Audio_Mixer_Design_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Audio_Mixer_Design_rst_processing_system7_0_100M_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_xlconcat_0_0/Audio_Mixer_Design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_xlconcat_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_xlconcat_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_axi_to_audio_interface_0_0/Audio_Mixer_Design_axi_to_audio_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_axi_to_audio_interface_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_axi_to_audio_interface_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_top_level_0_0/Audio_Mixer_Design_top_level_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_top_level_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_top_level_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_FILTER_IIR_0_0/Audio_Mixer_Design_FILTER_IIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_FILTER_IIR_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_FILTER_IIR_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_FILTER_IIR_1_0/Audio_Mixer_Design_FILTER_IIR_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_FILTER_IIR_1_0 || ORIG_REF_NAME==Audio_Mixer_Design_FILTER_IIR_1_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_Volume_Pregain_0_0/Audio_Mixer_Design_Volume_Pregain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_Volume_Pregain_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_Volume_Pregain_0_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_Volume_Pregain_1_0/Audio_Mixer_Design_Volume_Pregain_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_Volume_Pregain_1_0 || ORIG_REF_NAME==Audio_Mixer_Design_Volume_Pregain_1_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_axi_to_audio_interface_1_0/Audio_Mixer_Design_axi_to_audio_interface_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_axi_to_audio_interface_1_0 || ORIG_REF_NAME==Audio_Mixer_Design_axi_to_audio_interface_1_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_xbar_0/Audio_Mixer_Design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_xbar_0 || ORIG_REF_NAME==Audio_Mixer_Design_xbar_0}]

# IP: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_auto_pc_0/Audio_Mixer_Design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_auto_pc_0 || ORIG_REF_NAME==Audio_Mixer_Design_auto_pc_0}]

# XDC: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_processing_system7_0_0/Audio_Mixer_Design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_processing_system7_0_0 || ORIG_REF_NAME==Audio_Mixer_Design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_rst_processing_system7_0_100M_0/Audio_Mixer_Design_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Audio_Mixer_Design_rst_processing_system7_0_100M_0}]

# XDC: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_rst_processing_system7_0_100M_0/Audio_Mixer_Design_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Mixer_Design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Audio_Mixer_Design_rst_processing_system7_0_100M_0}]

# XDC: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_rst_processing_system7_0_100M_0/Audio_Mixer_Design_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_xbar_0/Audio_Mixer_Design_xbar_0_ooc.xdc

# XDC: bd/Audio_Mixer_Design/ip/Audio_Mixer_Design_auto_pc_0/Audio_Mixer_Design_auto_pc_0_ooc.xdc

# XDC: bd/Audio_Mixer_Design/Audio_Mixer_Design_ooc.xdc
